### PR TITLE
Getting relative path for uploaded image, instead of absolute

### PR DESCRIPTION
**Pull request by artshevtsov**
Modern sites use relative path for images, so I fixed absolute path to relative

### CODE REVIEW

**Comment by artshevtsov** [comment]
I don't know how to pass Travis CI, I have run all tasks, and commited updated files/
I have changed only one line:
https://github.com/orthes/medium-editor-insert-plugin/pull/455/commits/de0d95e7d067318768977f003270013339811cd5#diff-2627f4673527bccc425ad1f8f9e933b7R389

**Comment by orthes** [comment]
@artshevtsov Good catch. But please submit only your first commit (https://github.com/orthes/medium-editor-insert-plugin/pull/455/commits/de0d95e7d067318768977f003270013339811cd5) as a pull request. Do not submit dist folder or other unrelated files.

**Comment by artshevtsov** [comment]
Done!

**Comment by artshevtsov** [comment]
Done

**Comment by orthes** [comment]
Thanks. I'll have to figure out why Travis is failing. But that has nothing to do with your changes.

**Pull request merged**
