### PR TITLE
Calculate button position with scroll top

### PR DESCRIPTION
**Pull request by suskind**
Needs to use scroll top to calculate button top position

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you provide a jsfiddle that fail without your change?

**Comment by suskind** [comment]
The problem is with jQuery version 

Using version 2 (https://code.jquery.com/jquery-2.2.0.js) it fails 

I've tried it in your demo (http://linkesch.com/medium-editor-insert-plugin/) using Firefox Addon PourBico  replacing 

    <script src="bower_components/jquery/dist/jquery.js"></script> 
with 
    <script src="//code.jquery.com/jquery-2.2.0.js"></script> 

I have 2 samples here using all the resources from your demo but with different jQuery versions 

http://cloudpt.pdvel.com/work/medium-editor/test-jquery1.html 

http://cloudpt.pdvel.com/work/medium-editor/test-jquery2.html 

And btw, in your bower package you have jQuery version 2

**Comment by orthes** [comment]
I tried both demos and both works for me correctly. I tried it in Chrome and Firefox. What browser do you use?

**Comment by suskind** [comment]
Probably you have a big resolution. In "test-jquery2.html" make it to start having scroll and scroll down a bit and click on the editor to see the button.

**Comment by orthes** [comment]
Sorry @suskind, I've completely forgotten about this PR. My bad. 

You're right, I was able to reproduce it in Firefox. It looks like Firefox issue, because Chrome works correctly. But your fix also works only in Firefox and screws up Chrome.

Can you think about an universal solution that would work in both jQuery 1 and 2 and in all major browsers?

**Comment by trimeyko** [comment]
@orthes near the same issue when editor placed in scrollable container, this can be fixed by relative position of editor itself to handle position more correctly, but in case when editor also have scrolling top calculations doesn't take into mind $p.parent().scrollTop() value.

**Comment by orthes** [comment]
Fixed in #356

**Pull request closed without merging**
