### PR TITLE
add fileDeleteOptions

### PR DESCRIPTION
**Pull request by jackyzhai**
This should work. I'm not very familiar w/ the codebase, so please have a look before merging in. Thanks for the awesome work.

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you remove dist files from your commits?
Also, just to be sure, if I want to use your new option, I just need to do sth like that,  right?

```js
$('.editable').mediumInsert({
    enabled: true,
    addons: {
        images: {
            label: '<span class="fa fa-camera"></span>',
            fileDeleteOptions: {
                headers: {
                    'X-CSRF-TOKEN': 'MyAwesomeToken'
                }
            }
        }
    }
});
```

**Comment by j0k3r** [comment]
Also, we'll need to update the wiki accordingly.

**Comment by j0k3r** [comment]
See #263

**Comment by jackyzhai** [comment]
I submitted another PR for this.
 https://github.com/orthes/medium-editor-insert-plugin/pull/263
You are right. Just note that the old options are still available. The way I use it is:

        $('.editable').mediumInsert({
            addons: {
                images: {
                    deleteScript: '/images/delete',
                    deleteMethod: 'POST',
                    fileDeleteOptions: {
                        headers: {
                            'X-CSRF-TOKEN': Cookies.get('X-CSRF-Token')
                        }
                    }
                }
            }
        });

**Comment by j0k3r** [comment]
Thanks :+1:

**Pull request closed without merging**
