### PR TITLE
#239: The "elementsContainer" option on medium-editor is not been con…

### PR DESCRIPTION
**Pull request by patrinhani-ciandt**
…sidered for the Images toolbar positioning

### CODE REVIEW

**Comment by orthes** [comment]
Thank you

**Comment by orthes** [comment]
Can you just remove /dist files from the PR and submit only /src?

**Comment by patrinhani-ciandt** [comment]
Ow ok .. For sure ... Sorry man

On Sunday, 22 November 2015, Pavel Linkesch <notifications@github.com>
wrote:

> Can you just remove /dist files from the PR and submit only /src?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orthes/medium-editor-insert-plugin/pull/240#issuecomment-158737807>
> .
>


-- 
*Vinicius Patrinhani* • Software Architect
CI&T • Collaborate. Innovate. Transform.
+55 19 2102.4556 • patrinhani@ciandt.com • ciandt.com




"We develop people before we develop software" - Cesar Gon, CEO

"Win the game by learning faster!" - Cesar Gon, CEO

**Comment by patrinhani-ciandt** [comment]
@orthes The dist files was already removed and i applied the same solution to the Embeds plugin.

**Comment by orthes** [comment]
Great :+1: Thank you.

**Pull request merged**
