### PR TITLE
fix auto sumbitting bug

### PR DESCRIPTION
**Pull request by KazuyaHara**
I made PR #366 (and merged) but it was not enough to solve auto submitting bug. So I made some update. Please check and confirm this.

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you please remove dist files from the PR? Thanks

**Comment by lauranjansen** [comment]
I think with this update some of the CSS is also breaking, so that might need to be looked at as well.

**Comment by KazuyaHara** [comment]
@j0k3r Oops, thank you for reminding me. I removed dist files.

**Comment by KazuyaHara** [comment]
@lauranjansen Could you tell me wichi part of CSS is broken? I don't touch any of CSSs in this PR.

**Comment by lauranjansen** [comment]
I'm sorry, it wasn't actually your update that broke it, but when the anchor tags were changed to buttons, the CSS wasn't updated to reflect this. The result is that some of the buttons aren't styled like the anchor tags were. I'll create a separate issue for this, since it isn't really directly related to your PR.

**Comment by KazuyaHara** [comment]
I got it, thanks.

**Comment by j0k3r** [comment]
I merged it manually.
I wanted you not to remove file from the repo but remove modification done on dist files from your PR, sorry, I wasn't clear.

Thanks for the fix anyway :+1:

**Pull request closed without merging**
