### PR TITLE
Add a rotate animation on button

### PR DESCRIPTION
**Pull request by j0k3r**
When you click to show the addons button, the main button will rotate (like on medium.com) and the addons list will show up in fade mode (like on medium.com).

Before:

medium-insert-before

After:

medium-insert-after

:warning:  **Downside:**
I've commented one test..
The test which check that the button is hidden when you re-click on it. 

Because with the `fadeToggle` the `display` is still `block` until `opacity` reach 0, then `display` will be `none`. I didn't succeed in using [`async()`](https://api.qunitjs.com/async/) in qunit to test that behavior.

### CODE REVIEW

**Comment by orthes** [comment]
Testing if class was added/removed is much more reliable than testing for css attribute. (I know this know, not when I wrote those tests). So your solution is good.

**Comment by j0k3r** [comment]
Should I remove the commented test then ?

**Comment by orthes** [comment]
Yes, you can remove the commented test.

**Comment by orthes** [comment]
:+1:

**Comment by j0k3r** [comment]
Could you tag a new release regarding this merge?

**Comment by orthes** [comment]
Done

**Comment by j0k3r** [comment]
:+1: Thanks

**Pull request merged**
