### PR TITLE
Bower and grunt should be dev dependencies

### PR DESCRIPTION
**Pull request by dazorni**
Since you are using Bower for package management and Grunt for automating development tasks, they should be installed as one of the dev dependencies.

### CODE REVIEW

**Comment by orthes** [comment]
Hm. This is not a standard way of doing this as far as I know. Both bower and grunt docs advice to install bower and grunt-cli globally. Can you point me to a source (official docs, github discussion, etc.) that would suggest otherwise?

**Comment by dazorni** [comment]
It helps a lot for user who haven't installed grunt and bower globally to start contributing to your library. Actually the only requirement i want globally is npm.

I didn't found a info that i have to install it globally, i just found a part in the documentation of grunt http://gruntjs.com/installing-grunt#overview

> Grunt and Grunt plugins should be defined as devDependencies in your project's package.json.

All i want is an easy start for other developers, nothing more.

**Comment by orthes** [comment]
Grunt and grunt plugins yes. But we're talking about grunt-cli, which should be installed globally.

> In order to get started, you'll want to install Grunt's command line interface (CLI) globally. 
http://gruntjs.com/getting-started

**Comment by dazorni** [comment]
Okay, but there is no reason why. Do you know any reasons?
Or any reason why we should not include it as devDependencies?

**Pull request closed without merging**
