### PR TITLE
Add support for editableInput event - closes #212

### LINKED ISSUE #212: Capture DOM changes
Hi All,

How can I capture the modification on contenteditable when editing the image, delte or grid button for exemple.

this method below as described on medium-editor docs not be fired with image insert plugin toolbar but it fire when the contenteditable change from clicking on buttons in the toolbar 

```js
var editor = new MediumEditor('.editable');
editor.subscribe('editableInput', function (event, editable) {
    // Do some work
});
```

### PR DESCRIPTION
**Pull request by orthes**
I added a support for new ```editableInput``` event and tests run successfully in a browser, but in CLI it returns this error: **beforeEach failed on image preview: 'undefined' is not a function (evaluating 'this.handleDrag.bind(this)')**.

It's coming from MediumEditor. When I try to disable ```imageDragging``` in the editor, the error shifts to another extension (```this.handlePaste.bind(this)```). When I disable ```paste``` it continues to jump to yet another extension.

@j0k3r can you help me with that? You have deeper insight into MediumEditor than me. Am I missing something? Thanks.

### CODE REVIEW

**Comment by j0k3r** [comment]
I have looked at this problem and don't understand why it fails.
It fails as soon as you define the editor, no matter if your are using it after.

```js
$('#qunit-fixture').html('<div class="editable"></div>');
this.$el = $('.editable');

// only this line kill the test suite
this.editor = new MediumEditor('.editable');
```

And then I've no idea why `this.handleDrag.bind(this)` is undefined..

@nmielnik do you any clues about that? :confused:

**Comment by nmielnik** [comment]
hmmm, spent some time looking at this, no ideas just yet, I'm not too familiar with how the code is setup so I'll have to look more into it later.

**Comment by orthes** [comment]
It looks like a problem with QUnit. I will migrate all tests to Jasmine, since it's also used by the editor.

**Comment by orthes** [comment]
I rebased it to master and it looks like ditching Qunit in favour of Jasmine worked.

**Comment by j0k3r** [comment]
Good to merge then :+1:

**Pull request merged**
