### PR TITLE
add fileDeleteOptions

### LINKED ISSUE #248: Deletion of image failed because of CSRF token
For file uploads, we have fileUploadOptions, so that I can set 

    headers: {
        'X-CSRF-TOKEN': Cookies.get('X-CSRF-Token')
    }

However, it's not possible for deletions, any solutions? maybe something like fileDeleteOptions?

### PR DESCRIPTION
**Pull request by jackyzhai**
This is a clean version without changes in dist and package.json.

I do recommend adding a main field in package.json tho, so that people can use webpack.

Fix #248

### CODE REVIEW

**Comment by j0k3r** [comment]
Yeah, you could re-add the main field in package.json :+1: 

Also, I'll re-add my question:
Just to be sure, if I want to use your new option, I just need to do sth like that,  right?

```js
$('.editable').mediumInsert({
    enabled: true,
    addons: {
        images: {
            label: '<span class="fa fa-camera"></span>',
            fileDeleteOptions: {
                headers: {
                    'X-CSRF-TOKEN': 'MyAwesomeToken'
                }
            }
        }
    }
});
```

**Comment by jackyzhai** [comment]
Paste my answer here as well.

You are right. Just note that the old options are still available. The way I use it is:

    $('.editable').mediumInsert({
        addons: {
            images: {
                deleteScript: '/images/delete',
                deleteMethod: 'POST',
                fileDeleteOptions: {
                    headers: {
                        'X-CSRF-TOKEN': Cookies.get('X-CSRF-Token')
                    }
                }
            }
        }
    });

Sure, I'll add package.json back.

**Comment by j0k3r** [comment]
@orthes are you ok with that?
We'll need to update the doc accordingly.

**Comment by orthes** [comment]
:+1:

**Comment by j0k3r** [comment]
Thanks @jackyzhai !

**Comment by j0k3r** [comment]
Doc updated :white_check_mark: 
https://github.com/orthes/medium-editor-insert-plugin/wiki/v2.x-Configuration

**Comment by jackyzhai** [comment]
Thanks guys.

**Comment by ideadx** [comment]
@jackyzhai Thanks.

**Comment by ideadx** [comment]
I updated plugin and Delete Request is no longer been called when I remove the image?


deleteScript: '{!! action('XXX\JoyController@putSomeMethod') !!}',
 deleteMethod: 'PUT',
fileDeleteOptions: {
        _token: "{!! Session::getToken() !!}",
            id : 1
  },

**Pull request merged**
