### PR TITLE
Added deleteMethod option (#205)

### PR DESCRIPTION
**Pull request by bertzzie**
Hello,

This is the fix I propose for #205. All test passed in testem, for the following browsers:

Chrome 43.0.2357.130 (64-bit)
Safari 8.0.7 (10600.7.12)
Firefox 38.0.5

We'll need to update the documentation at the wiki too (I'd be glad to do it). Should we wait until the next version is released for that?

### CODE REVIEW

**Comment by bertzzie** [comment]
It seems like the build failed on travis. I'm sorry but I'm not sure what I did wrong :(

What should I do to fix this?

**Comment by j0k3r** [comment]
You should update this test: https://github.com/orthes/medium-editor-insert-plugin/blob/master/test/images.js#L306-L323

You can replace `post` by `ajax`.

And yes you can update the wiki as soon as this PR will be merged.

**Comment by bertzzie** [comment]
@j0k3r it passes now. Thank you very much for your guidance.

**Comment by j0k3r** [comment]
@orthes Any objection to this? :smiley:

**Comment by orthes** [comment]
:+1:

**Comment by j0k3r** [comment]
Thanks @bertzzie :smile:

**Pull request merged**
