### PR TITLE
Adding the possibility to inactive image drag and drop

### PR DESCRIPTION
**Pull request by enzoz**
Adding the possibility to users configure if drag and drop is active or not.

``` javascript
$('element').mediumInsert({
  editor: mediumEditor,
  addons: {
    images: {
      useDragAndDrop: false
    }
  }
});
```

I'm not sure about setting in image tag draggable as false and setting onmousedown to return false.

### CODE REVIEW

**Comment by MozMorris** [comment]
@orthes you removed this config. Do you know if there is another way to achieve this?

**Comment by j0k3r** [comment]
You can disabled it [in MediumEditor directly](https://github.com/yabwe/medium-editor/blob/master/OPTIONS.md#disabling-image-dragging).

**Comment by MozMorris** [comment]
@j0k3r thanks. I already tried that but no luck. As I understand it, that only prevents images being drag 'n dropped into the content-editable.

**Comment by MozMorris** [comment]
@j0k3r I'm an idiot. I'm posting this under the issue that relates to exactly what I just described. Sorry.

**Pull request merged**
