### PR TITLE
Ability to add upload failed callback to options

### PR DESCRIPTION
**Pull request by dazorni**
> Resolves: #350 

Maybe we should talk about the parameters we could send to the callback

## Todos

- [ ] Update wiki and add callback to options

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you not commit dist files please? Thanks

**Comment by dazorni** [comment]
I removed the dist files. I wasn't sure about your work process. Thanks 👍

**Comment by orthes** [comment]
@dazorni Thanks! Can you update wiki to reflect the changes?

**Comment by dazorni** [comment]
@orthes Done

**Comment by orthes** [comment]
@dazorni Thanks

**Pull request merged**
